/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {Button, Platform, StyleSheet, Text, View} from 'react-native';
import ReactNativeBrotherPrinters from 'react-native-brother-printers';

export default class App extends Component<{}> {
  state = {
    status: 'starting',
    message: '--'
  };

  componentDidMount() {
  }

  render() {
    return (
      <View style={styles.container}>
        <Text>
          Hi
        </Text>
        <Button title="Test" onPress={() => {
          ReactNativeBrotherPrinters.sampleMethod('Testing', 123, (message) => {
            this.setState({
                status: 'native callback received',
              message
            });
          });
        }}/>

        <Text style={styles.welcome}>☆ReactNativeBrotherPrinters example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
        <Text style={styles.instructions}>{this.state.message}</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
