/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {Button, ScrollView, StyleSheet, Text, TextInput, View} from 'react-native';
import {discoverPrinters, pingPrinter, printImage, registerBrotherListener} from 'react-native-brother-printers';
import ViewShot from "react-native-view-shot";

export default class App extends Component {
  state = {
    printer: null,
    ip: "",
  };

  componentDidMount() {
    registerBrotherListener("onDiscoverPrinters", (brotherPrinters) => {
      console.log("We found these listeners", brotherPrinters);

      if (brotherPrinters.length > 0) {
        this.setState({printer: brotherPrinters[0]});
      }
    });
  }

  render() {
    const {printer, ip} = this.state;

    return (
      <ScrollView style={{flex: 1}}>
        <ViewShot ref={(e) => {
          this.viewShot = e;
        }} options={{format: "jpg", quality: 0.9}}>
          <Text style={{fontSize: 24}}>
            Hello
          </Text>

          <Text style={{fontSize: 24}}>
            This is a test
          </Text>

          <Text style={{fontSize: 24}}>
            What is your name
          </Text>
        </ViewShot>

        <View style={styles.container}>
          <Text>
            Test Connection
          </Text>

          <Button title="Discover Readers" onPress={() => {
            discoverPrinters({}).then(() => {
              console.log("Discover Successful");
            }).catch(() => {
              console.log("Discover failed")
            });
          }}/>

          {printer && (
            <Button title="Print from Memory" onPress={() => {
              this.viewShot.capture().then(uri => {
                console.log("do something with ", uri);

                printImage(printer, uri, {autoCut: false}).then(() => {
                  console.log("Discover Successful");
                }).catch(() => {
                  console.log("Discover failed")
                });
              });
            }}/>
          )}

          <Button title="Print from Manual" onPress={() => {
            this.viewShot.capture().then(uri => {
              console.log("do something with ", uri);

              printImage({
                "ipAddress": "192.123.5.123",
                "modelName": "Brother QL-810W"
              }, uri, {autoCut: false}).then(() => {
                console.log("Discover Successful");
              }).catch(() => {
                console.log("Discover failed")
              });
            });
          }}/>

          <TextInput placeholder="Ip Address" value={ip} onChangeText={(ip) => this.setState({ip})}/>

          <Button title="Test Printer" onPress={() => {
            pingPrinter(ip).then(() => {
              alert("We found the printer");
            }).catch((err) => {
              console.log("Printer could not be accessed");

              console.log("Printer is dead", err);
            });
          }}/>
        </View>
      </ScrollView>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
